name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        stable: 'false'
        go-version: 1.17

    - name: Build
      run: make

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: |
          bin

    - name: Test
      run: go test -v ./...
